apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: account-deployment
spec:
  selector:
    matchLabels:
      app: account-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: account-deployment
    spec:
      containers:
        - name: account
          image: mahirolyuvob/account-manageloans
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_ACCOUNT_APPLICATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_ACCOUNT_APPLICATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_ACCOUNT_APPLICATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_ACCOUNT_APPLICATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_ACCOUNT_APPLICATION
---

apiVersion: v1
kind: Service
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  selector:
    app: account-deployment
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 0
  type: NodePort