apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer-deployment
spec:
  selector:
    matchLabels:
      app: customer-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-deployment
    spec:
      containers:
        - name: customer
          image: mahirolyuvob/customer-manageloans
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CUSTOMER_APPLICATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CUSTOMER_APPLICATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CUSTOMER_APPLICATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CUSTOMER_APPLICATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CUSTOMER_APPLICATION